import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TABLE "presentacion_catalogo_locales" (
  	"texto" jsonb DEFAULT '{"root":{"type":"root","direction":"ltr","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"direction":"ltr","format":"","indent":0,"children":[{"type":"text","version":1,"detail":0,"format":0,"mode":"normal","style":"","text":"Hola, os presentamos el nuevo programa de préstamos de material de PAFE. Mediante esta herramienta tendréis acceso a vídeos, juegos y libros. El préstamo durará un mes, siendo de martes de reunión a martes de reunión (aunque podréis hacer la reserva antes para que tengáis listo el material en la reunión). Se podrá realizar una prórroga de 2 semanas avisando una semana antes de que termine el plazo del préstamo. En caso de devolución tardía, tened en cuenta que esto puede afectar a otras personas del equipo que deseen hacer uso del mismo. Por otro lado, en caso de ruptura o pérdida, el usuario responsable deberá comprar uno similar y entregarlo (en caso de tener cualquier duda, podéis contactar con nosotros para que os asesoremos)."}]},{"type":"paragraph","version":1,"direction":"ltr","format":"","indent":0,"children":[{"type":"text","version":1,"detail":0,"format":0,"mode":"normal","style":"","text":"El catálogo es un material vivo que lo construimos entre todos y todas. Si usáis un material y queréis aportar sugerencias sobre cómo usarlo, para qué perfiles de casos y familias o con qué objetivos, contádnoslo. Y si queréis añadir algún documento descargable, referencia de vídeo o libro en formato electrónico, envíadlo a "},{"type":"link","version":3,"direction":"ltr","format":"","indent":0,"fields":{"linkType":"custom","newTab":false,"url":"mailto:pafe@agintzari.eus"},"children":[{"type":"text","version":1,"detail":0,"format":0,"mode":"normal","style":"","text":"pafe@agintzari.eus"}]},{"type":"text","version":1,"detail":0,"format":0,"mode":"normal","style":"","text":"."}]}]}}'::jsonb,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  
  ALTER TABLE "presentacion_catalogo_locales" ADD CONSTRAINT "presentacion_catalogo_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."presentacion_catalogo"("id") ON DELETE cascade ON UPDATE no action;
  CREATE UNIQUE INDEX "presentacion_catalogo_locales_locale_parent_id_unique" ON "presentacion_catalogo_locales" USING btree ("_locale","_parent_id");
  ALTER TABLE "presentacion_catalogo" DROP COLUMN "texto";`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   DROP TABLE "presentacion_catalogo_locales" CASCADE;
  ALTER TABLE "presentacion_catalogo" ADD COLUMN "texto" jsonb DEFAULT '{"root":{"type":"root","direction":"ltr","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"direction":"ltr","format":"","indent":0,"children":[{"type":"text","version":1,"detail":0,"format":0,"mode":"normal","style":"","text":"Hola, os presentamos el nuevo programa de préstamos de material de PAFE. Mediante esta herramienta tendréis acceso a vídeos, juegos y libros. El préstamo durará un mes, siendo de martes de reunión a martes de reunión (aunque podréis hacer la reserva antes para que tengáis listo el material en la reunión). Se podrá realizar una prórroga de 2 semanas avisando una semana antes de que termine el plazo del préstamo. En caso de devolución tardía, tened en cuenta que esto puede afectar a otras personas del equipo que deseen hacer uso del mismo. Por otro lado, en caso de ruptura o pérdida, el usuario responsable deberá comprar uno similar y entregarlo (en caso de tener cualquier duda, podéis contactar con nosotros para que os asesoremos)."}]},{"type":"paragraph","version":1,"direction":"ltr","format":"","indent":0,"children":[{"type":"text","version":1,"detail":0,"format":0,"mode":"normal","style":"","text":"El catálogo es un material vivo que lo construimos entre todos y todas. Si usáis un material y queréis aportar sugerencias sobre cómo usarlo, para qué perfiles de casos y familias o con qué objetivos, contádnoslo. Y si queréis añadir algún documento descargable, referencia de vídeo o libro en formato electrónico, envíadlo a "},{"type":"link","version":3,"direction":"ltr","format":"","indent":0,"fields":{"linkType":"custom","newTab":false,"url":"mailto:pafe@agintzari.eus"},"children":[{"type":"text","version":1,"detail":0,"format":0,"mode":"normal","style":"","text":"pafe@agintzari.eus"}]},{"type":"text","version":1,"detail":0,"format":0,"mode":"normal","style":"","text":"."}]}]}}'::jsonb;`)
}
