services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
      - node_modules:/workspace/node_modules:delegated
    command: sleep infinity
    environment:
      - NODE_ENV=development
    env_file:
      - ./.devcontainer.env
    depends_on:
      - devcontainer_db
    network_mode: host

  devcontainer_db:
    container_name: devcontainer_db
    image: postgres:17-alpine
    restart: always
    volumes:
      - ../.docker/devcontainer_postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=devsecret
      - POSTGRES_USER=devuser
      - POSTGRES_DB=devcontainer_db
    network_mode: host

volumes:
  postgres-data:
  node_modules:
