import { CatalogItem } from '@/modules/catalog/collections/CatalogItem'
import { DigitalItem } from '@/modules/catalog/collections/DigitalItem'
import { Reservation } from '@/modules/catalog/collections/Reservation'
import { Categories } from './Categories'
import { Cases } from './Cases'
import { Media } from './Media'
import { Pages } from './Pages'
import { Posts } from './Posts'
import { Tasks } from './Tasks'
import { TasksCompleted } from './TasksCompleted'
import { ExternalResources } from './ExternalResources'
import { Files } from './Files'
import { Groups } from './Groups'
import { Users } from './Users'

export const collections = [Reservation, CatalogItem, DigitalItem, Cases, Tasks, TasksCompleted, ExternalResources, Categories, Groups, Media, Users, Pages, Posts, Files]
