import { COLLECTION_SLUG_CATALOG_ITEM } from "./CatalogItem"
import { COLLECTION_SLUG_RESERVATION } from "./Reservation"

export const CATALOG_COLLECTIONS_SLUGS = [
    COLLECTION_SLUG_CATALOG_ITEM,
    COLLECTION_SLUG_RESERVATION
]