import type { CodigoIdioma } from './localization'

/**
 * Los textos de la interfaz. El contenido (materiales, noticias, categorías)
 * se traduce en el panel; esto es lo que está escrito en la propia web.
 *
 * Los nombres propios no entran: PAFE, Google Doc, Google Form y las áreas del
 * tablón se escriben igual en los dos idiomas.
 */
const es = {
  entrar: 'Entrar',
  cerrar: 'Cerrar',
  buscar: 'Buscar',
  cargando: 'Cargando…',

  inicioBienvenida: 'Bienvenido a PAFE',
  inicioCalendario: 'Calendario',
  calAgenda: 'Agenda',
  calSemana: 'Semana',
  calHoy: 'Hoy',
  calNovedades: 'Novedades del tablón',
  calTodoElDia: 'Todo el día',
  calSinNada: 'No hay nada previsto',
  calSemanaAnterior: 'Semana anterior',
  calSemanaSiguiente: 'Semana siguiente',
  calVolverAHoy: 'Volver a hoy',
  calFallidos: 'Algunos calendarios no responden ahora mismo.',

  navInicio: 'Inicio',
  navForo: 'Foro',
  navWiki: 'Wiki',
  navMoodle: 'Moodle',
  navAdministracion: 'Administración',
  navAbrirMenu: 'Abrir menú',
  navMenu: 'Menú de navegación',

  loginTitulo: 'Iniciar sesión',
  loginConGoogle: 'Entrar con Google',
  loginEmail: 'Email',
  loginContrasena: 'Contraseña',
  loginCredencialesMal: 'Email o contraseña incorrectos',
  loginOlvidada: '¿Has olvidado tu contraseña?',
  loginEscribeEmail: 'Escribe tu email arriba para enviarte el enlace',
  loginCorreoFallo: 'No se pudo enviar el correo. Inténtalo de nuevo en unos minutos.',
  loginCuentasLasCrea:
    'Las cuentas las crea la asociación. Si no tienes acceso, contacta con tu profesional de referencia.',

  claveEstablecer: 'Establecer contraseña',
  claveNueva: 'Nueva contraseña',
  claveRepite: 'Repite la contraseña',
  claveGuardar: 'Guardar contraseña',
  claveNoCoinciden: 'Las contraseñas no coinciden',
  claveGuardada: 'Contraseña guardada. Redirigiendo al inicio de sesión…',
  claveEnlaceCaducado: 'El enlace no es válido o ha caducado.',
  claveEnlaceCaducadoLargo:
    'El enlace no es válido o ha caducado. Solicita uno nuevo desde la pantalla de inicio de sesión.',
  claveGuardando: 'Guardando…',
  claveVolver: 'Volver a iniciar sesión',

  catalogo: 'Catálogo',
  catalogoBuscarPorTitulo: 'Buscar por título…',
  catalogoSinResultados: 'No se han encontrado materiales con estos filtros.',
  catalogoTipo: 'Tipo',
  catalogoTodo: 'Todo el catálogo',
  catalogoTodosMateriales: 'Todos los materiales',
  catalogoRecursosExternos: 'Recursos externos',
  catalogoProgramasTecnicos: 'Programas técnicos',
  tipoReservable: 'Reservable',
  tipoDescargable: 'Descargable',
  tipoLibro: 'Libro',
  tipoJuego: 'Juego',
  tipoPrograma: 'Programa',
  catalogoReservables: 'Reservables',
  catalogoDescargables: 'Descargables',
  catalogoMaterial: 'Material',
  catalogoMaterialUno: 'material',
  catalogoMaterialVarios: 'materiales',
  catalogoLibros: 'Libros',
  catalogoJuegos: 'Juegos',
  catalogoFormato: 'Formato',
  catalogoVideo: 'Vídeo',
  catalogoTematica: 'Temática',
  catalogoEdad: 'Edad',
  catalogoDestinatario: 'Destinatario',
  catalogoTodasTematicas: 'Todas las temáticas',
  catalogoTodasEdades: 'Todas las edades',
  catalogoTodosDestinatarios: 'Todos los destinatarios',
  catalogoTodosFormatos: 'Todos los formatos',
  catalogoCategoria: 'Categoría',
  catalogoTodasCategorias: 'Todas las categorías',
  catalogoEnlaceWeb: 'Enlace web',
  catalogoRecursoExterno: 'Recurso externo',
  catalogoDescargar: 'Descargar',
  catalogoIrAReservar: 'Ir a reservar',
  catalogoVer: 'Ver',
  catalogoSaberMasDescargar: '¿Quieres saber algo más antes de descargarlo?',
  catalogoSaberMasReservar: '¿Quieres saber algo más antes de reservarlo?',
  catalogoSaberMasDetalle: '¿Quieres saber algo más de este material antes de reservarlo?',
  catalogoAportaciones: 'Aportaciones de las familias',
  catalogoDisponibles: 'Disponibles:',
  catalogoDisponiblesDe: '{libres} de {total}',

  reservaReservarLibro: 'Reservar libro',
  reservaReservarParaUsuario: 'Reservar para usuario',
  reservaEntraParaReservar: 'Debes iniciar sesión para poder reservar este libro',
  reservaErrorCrear: 'Error al crear la reserva:',
  reservaReservando: 'Reservando...',
  reservaSinReservasLibro: 'No hay reservas para este libro',
  reservaSinReservasActivas: 'No hay reservas activas',
  reservaSeleccionarUsuario: 'Seleccionar Usuario',
  reservaBuscarUsuario: 'Buscar por nombre o email...',
  reservaCargandoUsuarios: 'Cargando usuarios...',
  reservaErrorUsuarios: 'Error al cargar usuarios:',
  reservaSinUsuarios: 'No se encontraron usuarios',
  reservaMisPrestamos: 'Mis préstamos',
  reservaTabla: 'Reservas y préstamos',
  reservaCargandoReservas: 'Cargando reservas...',
  reservaErrorDevolver: 'Error al devolver el libro:',
  reservaDevolverEl: 'Devolver el {fecha}',
  reservaReposicionAntes: 'Reposición pendiente antes del {fecha}',

  estadoReservada: 'Pendiente de recoger',
  estadoActiva: 'En préstamo',
  estadoDevuelta: 'Devuelta',
  estadoPerdida: 'Perdida o rota',
  estadoCancelada: 'Cancelada',

  accionCancelar: 'Cancelar',
  accionDevolver: 'Devolver',
  accionRecogida: 'Registrar recogida',
  accionProrrogar: 'Prorrogar 2 semanas',
  accionMarcarPerdida: 'Marcar pérdida',
  accionReposicion: 'Registrar reposición',

  avisosSinAvisos: 'No tienes avisos',

  tablon: 'Tablón',
  tablonVer: 'Ver el tablón',
  foroVer: 'Ver foro',
  foroDescripcion: 'Todas las noticias y conversaciones de PAFE, organizadas por áreas.',
  foroAreas: 'Áreas del foro',
  foroActuales: 'Actuales',
  foroBuscar: 'Buscar por título',
  foroTemas: 'temas',
  foroTema: 'tema',
  foroPagina: 'Página {pagina} de {total}',
  foroPaginacion: 'Páginas del foro',
  foroVacio: 'No hay temas que coincidan con estos filtros.',
  foroVolver: 'Volver al foro',
  tablonCargando: 'Cargando el tablón…',
  tablonVacio: 'Todavía no hay nada publicado aquí.',
  tablonTodas: 'Todas',
  tablonFijada: 'Fijada',
  tablonArchivadas: 'Archivadas',
  tablonErrorCargar: 'No se pudo cargar el tablón. Recarga la página para volver a intentarlo.',
  respuestasVacio: 'Todavía no ha respondido nadie.',
  respuestasEscribe: 'Escribe tu respuesta…',
  respuestasRetirar: 'Retirar',
  respuestasRetirarMia: 'Retirar mi respuesta',
  respuestasErrorEnviar: 'No se pudo enviar.',
  respuestasErrorRetirar: 'No se pudo retirar.',

  cuestionarioGuiado: 'Cuestionario guiado',
  cuestionarioNoDisponible: 'El cuestionario no está disponible',
  cuestionarioDefinicionMal:
    'Su definición FlowGraph no es válida. Contacta con el equipo de PAFE.',
  cuestionarioComenzar: 'Comenzar',
  cuestionarioCompletado: 'Cuestionario completado',
  cuestionarioGuardando: 'Guardando tu respuesta…',
  cuestionarioGuardado: 'Tu respuesta se ha guardado correctamente.',
  cuestionarioReintentar: 'Reintentar envío',
  cuestionarioResultado: 'Resultado:',
  cuestionarioRecuperado:
    'Hemos recuperado tu sesión anterior; puedes continuar donde lo dejaste.',
  cuestionarioCargandoRecurso: 'Cargando recurso…',
  cuestionarioMaterialDescargable: 'Material descargable',

  pagAnterior: 'Anterior',
  pagSiguiente: 'Siguiente',
  pagIrAnterior: 'Ir a la página anterior',
  pagIrSiguiente: 'Ir a la página siguiente',
  pagMas: 'Más páginas',
} as const

export type Textos = Record<keyof typeof es, string>

const eu: Textos = {
  entrar: 'Sartu',
  cerrar: 'Itxi',
  buscar: 'Bilatu',
  cargando: 'Kargatzen…',

  inicioBienvenida: 'Ongi etorri PAFEra',
  inicioCalendario: 'Egutegia',
  calAgenda: 'Agenda',
  calSemana: 'Astea',
  calHoy: 'Gaur',
  calNovedades: 'Iragarki-taulako berriak',
  calTodoElDia: 'Egun osoa',
  calSinNada: 'Ez dago ezer aurreikusita',
  calSemanaAnterior: 'Aurreko astea',
  calSemanaSiguiente: 'Hurrengo astea',
  calVolverAHoy: 'Gaurkora itzuli',
  calFallidos: 'Egutegi batzuek ez dute erantzuten une honetan.',

  navInicio: 'Hasiera',
  navForo: 'Foroa',
  navWiki: 'Wikia',
  navMoodle: 'Moodle',
  navAdministracion: 'Administrazioa',
  navAbrirMenu: 'Menua ireki',
  navMenu: 'Nabigazio-menua',

  loginTitulo: 'Saioa hasi',
  loginConGoogle: 'Googlerekin sartu',
  loginEmail: 'Helbide elektronikoa',
  loginContrasena: 'Pasahitza',
  loginCredencialesMal: 'Helbide elektronikoa edo pasahitza okerra da',
  loginOlvidada: 'Pasahitza ahaztu duzu?',
  loginEscribeEmail: 'Idatzi zure helbide elektronikoa goian, esteka bidaltzeko',
  loginCorreoFallo: 'Ezin izan da mezua bidali. Saiatu berriro minutu batzuk barru.',
  loginCuentasLasCrea:
    'Kontuak elkarteak sortzen ditu. Sarbiderik ez baduzu, jarri harremanetan zure erreferentziazko profesionalarekin.',

  claveEstablecer: 'Pasahitza ezarri',
  claveNueva: 'Pasahitz berria',
  claveRepite: 'Errepikatu pasahitza',
  claveGuardar: 'Gorde pasahitza',
  claveNoCoinciden: 'Pasahitzak ez datoz bat',
  claveGuardada: 'Pasahitza gorde da. Saioa hasteko orrira eramaten…',
  claveEnlaceCaducado: 'Esteka ez da baliozkoa edo iraungi egin da.',
  claveEnlaceCaducadoLargo:
    'Esteka ez da baliozkoa edo iraungi egin da. Eskatu beste bat saioa hasteko pantailatik.',
  claveGuardando: 'Gordetzen…',
  claveVolver: 'Saioa hastera itzuli',

  catalogo: 'Katalogoa',
  catalogoBuscarPorTitulo: 'Bilatu izenburuaren arabera…',
  catalogoSinResultados: 'Ez da materialik aurkitu iragazki hauekin.',
  catalogoTipo: 'Mota',
  catalogoTodo: 'Katalogo osoa',
  catalogoTodosMateriales: 'Material guztiak',
  catalogoRecursosExternos: 'Kanpoko baliabideak',
  catalogoProgramasTecnicos: 'Programa teknikoak',
  tipoReservable: 'Erreserbagarria',
  tipoDescargable: 'Deskargagarria',
  tipoLibro: 'Liburua',
  tipoJuego: 'Jokoa',
  tipoPrograma: 'Programa',
  catalogoReservables: 'Erreserbagarriak',
  catalogoDescargables: 'Deskargagarriak',
  catalogoMaterial: 'Materiala',
  catalogoMaterialUno: 'material',
  catalogoMaterialVarios: 'material',
  catalogoLibros: 'Liburuak',
  catalogoJuegos: 'Jokoak',
  catalogoFormato: 'Formatua',
  catalogoVideo: 'Bideoa',
  catalogoTematica: 'Gaia',
  catalogoEdad: 'Adina',
  catalogoDestinatario: 'Hartzailea',
  catalogoTodasTematicas: 'Gai guztiak',
  catalogoTodasEdades: 'Adin guztiak',
  catalogoTodosDestinatarios: 'Hartzaile guztiak',
  catalogoTodosFormatos: 'Formatu guztiak',
  catalogoCategoria: 'Kategoria',
  catalogoTodasCategorias: 'Kategoria guztiak',
  catalogoEnlaceWeb: 'Web esteka',
  catalogoRecursoExterno: 'Kanpoko baliabidea',
  catalogoDescargar: 'Deskargatu',
  catalogoIrAReservar: 'Erreserbatzera joan',
  catalogoVer: 'Ikusi',
  catalogoSaberMasDescargar: 'Deskargatu aurretik gehiago jakin nahi duzu?',
  catalogoSaberMasReservar: 'Erreserbatu aurretik gehiago jakin nahi duzu?',
  catalogoSaberMasDetalle: 'Material honi buruz gehiago jakin nahi duzu erreserbatu aurretik?',
  catalogoAportaciones: 'Familien ekarpenak',
  catalogoDisponibles: 'Eskuragarri:',
  catalogoDisponiblesDe: '{total}(e)tik {libres}',

  reservaReservarLibro: 'Liburua erreserbatu',
  reservaReservarParaUsuario: 'Erabiltzaile batentzat erreserbatu',
  reservaEntraParaReservar: 'Liburu hau erreserbatzeko saioa hasi behar duzu',
  reservaErrorCrear: 'Errorea erreserba sortzean:',
  reservaReservando: 'Erreserbatzen...',
  reservaSinReservasLibro: 'Ez dago erreserbarik liburu honetarako',
  reservaSinReservasActivas: 'Ez dago erreserba aktiborik',
  reservaSeleccionarUsuario: 'Erabiltzailea hautatu',
  reservaBuscarUsuario: 'Bilatu izenaren edo helbide elektronikoaren arabera...',
  reservaCargandoUsuarios: 'Erabiltzaileak kargatzen...',
  reservaErrorUsuarios: 'Errorea erabiltzaileak kargatzean:',
  reservaSinUsuarios: 'Ez da erabiltzailerik aurkitu',
  reservaMisPrestamos: 'Nire maileguak',
  reservaTabla: 'Erreserbak eta maileguak',
  reservaCargandoReservas: 'Erreserbak kargatzen...',
  reservaErrorDevolver: 'Errorea liburua itzultzean:',
  reservaDevolverEl: '{fecha}(e)an itzuli',
  reservaReposicionAntes: 'Ordezkapena {fecha} baino lehen egin behar da',

  estadoReservada: 'Jasotzeko zain',
  estadoActiva: 'Mailegatuta',
  estadoDevuelta: 'Itzulita',
  estadoPerdida: 'Galduta edo hautsita',
  estadoCancelada: 'Bertan behera utzita',

  accionCancelar: 'Bertan behera utzi',
  accionDevolver: 'Itzuli',
  accionRecogida: 'Jasotzea erregistratu',
  accionProrrogar: '2 astez luzatu',
  accionMarcarPerdida: 'Galdutzat eman',
  accionReposicion: 'Ordezkapena erregistratu',

  avisosSinAvisos: 'Ez duzu abisurik',

  tablon: 'Iragarki-taula',
  tablonVer: 'Iragarki-taula ikusi',
  foroVer: 'Foroa ikusi',
  foroDescripcion: 'PAFEko albiste eta elkarrizketa guztiak, arloka antolatuta.',
  foroAreas: 'Foroko arloak',
  foroActuales: 'Unekoak',
  foroBuscar: 'Izenburuaren arabera bilatu',
  foroTemas: 'gai',
  foroTema: 'gai',
  foroPagina: '{pagina}. orria, guztira {total}',
  foroPaginacion: 'Foroko orriak',
  foroVacio: 'Ez dago iragazki hauekin bat datorren gairik.',
  foroVolver: 'Forora itzuli',
  tablonCargando: 'Iragarki-taula kargatzen…',
  tablonVacio: 'Oraindik ez da ezer argitaratu hemen.',
  tablonTodas: 'Guztiak',
  tablonFijada: 'Finkatuta',
  tablonArchivadas: 'Artxibatuak',
  tablonErrorCargar: 'Ezin izan da iragarki-taula kargatu. Kargatu orria berriro saiatzeko.',
  respuestasVacio: 'Oraindik inork ez du erantzun.',
  respuestasEscribe: 'Idatzi zure erantzuna…',
  respuestasRetirar: 'Kendu',
  respuestasRetirarMia: 'Nire erantzuna kendu',
  respuestasErrorEnviar: 'Ezin izan da bidali.',
  respuestasErrorRetirar: 'Ezin izan da kendu.',

  cuestionarioGuiado: 'Galdetegi gidatua',
  cuestionarioNoDisponible: 'Galdetegia ez dago eskuragarri',
  cuestionarioDefinicionMal:
    'Haren FlowGraph definizioa ez da baliozkoa. Jarri harremanetan PAFEko taldearekin.',
  cuestionarioComenzar: 'Hasi',
  cuestionarioCompletado: 'Galdetegia osatuta',
  cuestionarioGuardando: 'Zure erantzuna gordetzen…',
  cuestionarioGuardado: 'Zure erantzuna ondo gorde da.',
  cuestionarioReintentar: 'Bidalketa berriro saiatu',
  cuestionarioResultado: 'Emaitza:',
  cuestionarioRecuperado: 'Aurreko saioa berreskuratu dugu; utzi zenuen tokitik jarrai dezakezu.',
  cuestionarioCargandoRecurso: 'Baliabidea kargatzen…',
  cuestionarioMaterialDescargable: 'Deskargatzeko materiala',

  pagAnterior: 'Aurrekoa',
  pagSiguiente: 'Hurrengoa',
  pagIrAnterior: 'Aurreko orrira joan',
  pagIrSiguiente: 'Hurrengo orrira joan',
  pagMas: 'Orri gehiago',
}

const DICCIONARIOS: Record<CodigoIdioma, Textos> = { es, eu }

export const textosDe = (idioma: CodigoIdioma): Textos => DICCIONARIOS[idioma]

/** Rellena los huecos {nombre} de una plantilla del diccionario */
export const rellenar = (plantilla: string, valores: Record<string, string>): string =>
  plantilla.replace(/\{(\w+)\}/g, (original, clave) => valores[clave] ?? original)
